vich_uploader:
    db_driver: orm

    mappings:
        project_image:
            uri_prefix:         '%app.path.project_image%'
            upload_destination: '%kernel.project_dir%/public%app.path.project_image%'
            namer:              Vich\UploaderBundle\Naming\OrignameNamer
