vich_uploader:
    db_driver: orm

    mappings:
        project_image:
            uri_prefix: /images/projects
            upload_destination: '%kernel.project_dir%/public/images/projects'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
        skill_icon:
            uri_prefix: /images/skills/icons
            upload_destination: '%kernel.project_dir%/public/images/skills/icons'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
