vich_uploader:
    db_driver: orm

    mappings:
        skill_icon:
            uri_prefix:         '%app.path.skill_icon%'
            upload_destination: '%kernel.project_dir%/public%app.path.skill_icon%'
            namer:              Vich\UploaderBundle\Naming\OrignameNamer
        project_cover:
            uri_prefix:         '%app.path.project_cover%'
            upload_destination: '%kernel.project_dir%/public%app.path.project_cover%'
            namer:              Vich\UploaderBundle\Naming\OrignameNamer
